name: TestBuild1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies (packages)
        run: |
          curl -LO https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_macosx_x86_64
          sudo install -m755 ldid_macosx_x86_64 /usr/local/bin/ldid
          brew install 7zip

      - name: Compile
        run: IOS=1 FINAL=1 make

      - name: Zip packages folder
        run: 7z a packages.zip packages/

      - name: Upload zip to transfer.sh
        run: |
          UPLOAD_LINK=$(curl --upload-file ./packages.zip https://transfer.sh/packages.zip)
          echo "Uploaded to: $UPLOAD_LINK"
